apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtodoui
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: microtodoui
  template:
    metadata:
      labels:
        app: microtodoui
    spec:
      containers:
      - name: microtodoui
        image: rakeshacr.azurecr.io/microtodoui:v1
        ports:
        - containerPort: 80
          protocol: TCP